In [30]:
import numpy as np
import statsmodels.api as sm
import pandas as pd
from scipy.stats import norm
from scipy.stats import bernoulli
from scipy.stats import poisson
from scipy.optimize import minimize
import argparse
from GRA41522 import DataLoader, LoadSMdataset, Loadcsv
from GRA41522 import GLM, Normal, Bernoulli, Poisson

In [ ]:
parser = argparse.ArgumentParser()
parser.add_argument("model", dset =)

_StoreAction(option_strings=[], dest='model', nargs=None, const=None, default=None, type=None, choices=None, required=True, help=None, metavar=None)

In [ ]:
from sklearn.datasets import make_regression
x1, y1 = make_regression(n_samples=5, n_features=2, noise=1, random_state=42)

In [32]:
n = Normal(X, y)
n.fit()
print(n.beta)
n.predict()

[18.59492168 17.02196776]


array([ 6.88283029, 37.96868275, -8.3395354 ,  0.50560013, 42.42858783])

In [33]:
normal_mod = sm.GLM(y, X, family = sm.families.Gaussian())
res = normal_mod.fit()
print(res.params)
res.predict(X)

[18.59492167 17.0219678 ]


array([ 6.88283028, 37.9686828 , -8.3395354 ,  0.50560016, 42.42858784])

In [40]:
df = sm.datasets.spector.load_pandas()
Y = df.endog.iloc[:5]
x = df.exog.iloc[:5,:]
m = Bernoulli(x, Y)
m.fit()
print(m.beta)
print(m.predict(x))

[ 1.20297935 -0.26025476  0.1       ]
0    0.118661
1    0.095436
2    0.091095
3    0.596197
4    0.342216
dtype: float64


In [39]:
logit_mod = sm.GLM(Y, x, family = sm.families.Binomial())
res1 = logit_mod.fit()
print(res1.params)
print(res1.predict())

GPA     1.202978
TUCE   -0.260255
PSI     0.000000
dtype: float64
[0.11866125 0.09543633 0.09109472 0.5961965  0.3422164 ]


In [45]:
p = DataLoader(LoaderType= Loadcsv)
file_path="warpbreaks.csv"

In [50]:
p = pd.read_csv("warpbreaks.csv")
p.head()
Y2 = p['breaks']
X2 = p[['wool','tension']]
poi = Poisson(X2,Y2)
poi.fit()
poi.beta

array([1.85745987, 1.03961996])

In [51]:
poi.predict(X2)

0      1.000000
1      1.000000
2      1.000000
3      1.000000
4      1.000000
5      1.000000
6      1.000000
7      1.000000
8      1.000000
9      2.828142
10     2.828142
11     2.828142
12     2.828142
13     2.828142
14     2.828142
15     2.828142
16     2.828142
17     2.828142
18     7.998387
19     7.998387
20     7.998387
21     7.998387
22     7.998387
23     7.998387
24     7.998387
25     7.998387
26     7.998387
27     6.407440
28     6.407440
29     6.407440
30     6.407440
31     6.407440
32     6.407440
33     6.407440
34     6.407440
35     6.407440
36    18.121151
37    18.121151
38    18.121151
39    18.121151
40    18.121151
41    18.121151
42    18.121151
43    18.121151
44    18.121151
45    51.249188
46    51.249188
47    51.249188
48    51.249188
49    51.249188
50    51.249188
51    51.249188
52    51.249188
53    51.249188
dtype: float64

In [52]:
poisson_mod = sm.GLM(Y2, X2, family = sm.families.Poisson())
res3 = poisson_mod.fit()
res3.params

wool       1.85746
tension    1.03962
dtype: float64

In [53]:
res3.predict()

array([ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
        1.        ,  1.        ,  1.        ,  1.        ,  2.82814215,
        2.82814215,  2.82814215,  2.82814215,  2.82814215,  2.82814215,
        2.82814215,  2.82814215,  2.82814215,  7.998388  ,  7.998388  ,
        7.998388  ,  7.998388  ,  7.998388  ,  7.998388  ,  7.998388  ,
        7.998388  ,  7.998388  ,  6.40743962,  6.40743962,  6.40743962,
        6.40743962,  6.40743962,  6.40743962,  6.40743962,  6.40743962,
        6.40743962, 18.12115003, 18.12115003, 18.12115003, 18.12115003,
       18.12115003, 18.12115003, 18.12115003, 18.12115003, 18.12115003,
       51.24918813, 51.24918813, 51.24918813, 51.24918813, 51.24918813,
       51.24918813, 51.24918813, 51.24918813, 51.24918813])